### ISSUE TITLE
Doesn't get listed in Atom.io's packages

### ISSUE THREAD

**Issue by nrodriguez** [Floobits/floobits-atom#1]
Cannot install via the package installer within Atom.io

**Comment by ggreer** [comment]
Sorry, but this plugin isn't ready for usage yet. Give us a few weeks and we'll have something that doesn't beachball Atom and break randomly. :)

**Comment by nrodriguez** [comment]
Ah, sorry haha I happily await it then!

**Comment by sscotth** [comment]
:checkered_flag:

**Comment by kans** [comment]
We are still slowly working through bugs.  We will also have to rework some code to not use now deprecated APIs which will require UI changes.  Also, we need to make the plugin work on Linux and Windows.

**Comment by sscotth** [comment]
It is currently listed in the package repository, thus this issue is resolved.

**Comment by ggreer** [comment]
Yep, closing this.
