### ISSUE TITLE
resize floobits window

### ISSUE THREAD

**Issue by shadowbq** [Floobits/floobits-atom#100]
Add the ability to resize the floobits windows, or adjust it in the settings for the plugin.

**Comment by kans** [comment]
What do you mean?

**Comment by shadowbq** [comment]
When I'm not video chatting with my pair.. The "userlist panel" with the Icon of my gravatar is very large taking up substantial screen space on the atom ide. The ability to re-size that frame/window to a smaller size when not video chatting would increase my productivity.

**Comment by shadowbq** [comment]
228 px is hardcoded into three locations in the extension.

lib/common/mugshot.js 

``` javascript
9   const prefs = require("./userPref_model");
10  const WebRTC = require("./webrtc");
11  
12  const THUMB_WIDTH = 228;
13  const THUMB_HEIGHT = 228;
```

templates/user_view.js 

``` javascript
170     var canEdit = perms.indexOf("patch") !== -1,
171       src = this.props.user.gravatar;
172 
173     if (src) {
174       src += "?s=228";
```

lib/common/webrtc.js 

``` javascript
28      video: { optional: [
29        { facingMode: "user" },
30        { maxWidth: 228 },
31        { maxHeight: 228 },
```

**Comment by shadowbq** [comment]
adding a toggle user list panel to the "floobits menu > toggle user list panel" could help as knowing that closing the user list panel does not disconnect you from floobits workspace.

**Comment by ggreer** [comment]
Ah, I see what you mean now. I typically develop on a 12" screen, so I share your pain. I'm not sure what the best fix for this is, as I want it to be super-obvious when:
1. You're connected to a Floobits workspace.
2. Your picture is being taken. (If you have that option enabled.)

I'll figure out something.

**Comment by shadowbq** [comment]
Bubble up this code into a variable so we can have an option setting that can set the size to 114 or 228 in the extension setting for atom.

**Comment by kans** [comment]
@shadowbq 

Sorry for the late reply.  There has been a 'Floobits - Toggle User List' for a while now.
