### ISSUE TITLE
I can't add new lines to file eventhough I'm admin

### ISSUE THREAD

**Issue by buckdig** [Floobits/floobits-atom#119]

**Comment by buckdig** [comment]
I'm using floobits in Atom Windows.

**Comment by ggreer** [comment]
If you change your newlines from CR to LF, does that work around the problem?

**Comment by buckdig** [comment]
What is this anyway? And how can I do it? THanks

**Comment by ggreer** [comment]
Open a file, then ctrl + shift + p: Line Ending Selector: Convert to LF.
Then try typing.

I think I know what the issue is. I can reproduce it using Atom on Windows, but it will take a little longer to fix. Until then, this work-around should help.
