### ISSUE TITLE
Changing a file name in Atom causes file to disapear 

### ISSUE THREAD

**Issue by rdedeus** [Floobits/floobits-atom#129]
This seems to happen only when you rename a file inside of Atom in an active floobits workspace.
I am using Windows 10 Atom 1.8.0.

**Comment by kans** [comment]
Did you happen to move the file to a folder outside of the workspace, or did you just change the name?

**Comment by rdedeus** [comment]
I just changed the name. I did not move it to another folder. After restarting the computer, I can't replicate the issue anymore.

**Comment by Bdthomson** [comment]
This has happened to me on numerous occasions... the files are lost completely unless you've backed them up with VCS recently.
