### ISSUE TITLE
persistent.json doesn't respect the configured share_dir.

### ISSUE THREAD

**Issue by phyllisstein** [Floobits/floobits-atom#166]
Hey Flooers! I wanted to flag that in the Atom plugin, the configured `share_dir` isn't respected when generating `persistent.json`: <https://github.com/Floobits/floobits-atom/blob/master/lib/common/persistentjson.js#L9>. It's a minor quibble with what otherwise seems like a gorgeous package, but I like to keep my stateful config directories hidden from the Finder. My `.floorc.json` looks like this, incidentally:

```json
{
  "auth": {
    "floobits.com": {
      "username": "phyllisstein",
      "api_key": "...",
      "secret": "..."
    },
    "share_dir": "~/.floobits/",
    "flootty_safe": false
  }
}

```

Thanks in advance for taking a look! Appreciate all your work on Floobits.

**Comment by kans** [comment]
Thanks for the report.
