### ISSUE TITLE
Status bar for showing we are connected.

### ISSUE THREAD

**Issue by btipling** [Floobits/floobits-atom#28]

**Comment by kans** [comment]
A status bar can be added to the bottom by making a new atom panel.  There is an example of this already in the code base for the webrtc stuff.  See https://github.com/Floobits/floobits-atom/blob/master/lib/floobits.js#L221 and https://atom.io/docs/api/v0.188.0/Workspace#instance-addBottomPanel.

We want to use React, but atom only supports Custom HTML elements.  We have an element factory that takes a react component and creates an element wrapper.  The wrapper can be passed directly to atom.  It also adds a destroy method that interfaces with atom for easy removal.  

**NOTE** react views must live in templates, must have the header: `/** @jsx React.DOM */`, should contain "use strict", and you must restart the watcher.
