### ISSUE TITLE
Deprecated Atom APIs will be removed June 1st

### ISSUE THREAD

**Issue by benogle** [Floobits/floobits-atom#43]
Atom will no longer load this package after June 1st without changes. There are a couple deprecations on the latest version (`0.4.2`) of this package:
1. The context menu CSON format has changed. Please see https://atom.io/docs/api/latest/ContextMenuManager#context-menu-cson-format for more info.
2. Use ::getDirectories instead
3. Use ::getRepositories instead
4. Call ::getActiveTextEditor instead

Visit https://gist.github.com/benogle/6d09e295c84b717ef9b4 and search for your package name to see up-to-date deprecations.

If this package has been replaced by another package or functionality in core, please reply with this information.

See https://github.com/atom/atom/issues/6867 for more info. Thanks!

**Comment by sglyon** [comment]
Any chance these deprecations can be resolved?

**Comment by kans** [comment]
@spencerlyon2 
I will try to have everything fixed by the end of today.

**Comment by sglyon** [comment]
Awesome, that would be great!

**Comment by ggreer** [comment]
OK, the latest 0.5.0 release should have all the fixes needed to use with the latest Atom. Thanks for being patient.

**Comment by sglyon** [comment]
Great work. Thanks for being so quick.
