### ISSUE TITLE
Clean up following options in command palette

### ISSUE THREAD

**Issue by btipling** [Floobits/floobits-atom#64]
Add "unfollow" command when following.
Continue to show "follow" even if already following to the let the user switch to who they're following so they don't have to unfollow whatever they're following first.
Finally also lave the unfollow option in follow in case they were going to follow someone but decided to not follow anyone anymore.

**Comment by kans** [comment]
If you break it up into two commands, you need two keybinds...  maybe we could just alias it?

**Comment by btipling** [comment]
Why do you need keybinds?
