### ISSUE TITLE
Store highlights by connection id, not username, clean up highlights after client disconnects

### ISSUE THREAD

**Issue by btipling** [Floobits/floobits-atom#69]
In every other client we store highlights by connection id and in atom it's by username so if you have multiple connections (i.e. multiple tabs open) the last one to send highlights wipes out the highlights from other connections. 

This explains a lot of wonkiness. 

I don't think you'd ever want highlights by username it ought to always be by connection id because if you are open in atom and following in the web editor the web editor in follow mode is going to ruin anything you're trying to highlight in atom or some other editor.

It may also explain the flickering

May be related to #59

**Comment by kans** [comment]
I think the flickering is also caused by highlights in follow mode external to atom.
