### ISSUE TITLE
Easier Audio-Only Toggle?

### ISSUE THREAD

**Issue by epmatsw** [Floobits/floobits-atom#77]
It would be nice to be able to toggle video on or off without having to open settings, change a setting, and restart the video conference. Appear.in has this feature, and it's really useful to be able to quickly disable video if something distracting is going on in the background of your video.

**Comment by kans** [comment]
@epmatsw 

Do you mean you would like to disable your video but keep the audio going?

**Comment by epmatsw** [comment]
Yep! You can do it now by switching to audio only mode in settings and restarting your video chat, but it'd be nice to be able to keep the same stream going.

**Comment by epmatsw** [comment]
A more obvious mute button (is there one now?) would also be good. A few team members have dogs and/or children and it's just easier for them to turn their audio off unless they're actively talking.

**Comment by ggreer** [comment]
For muting: If you're on a mac, I highly recommend [Shush](http://mizage.com/shush/). Both kans and I use it.

We'll also work on an easy mute button. We have one in the web editor, but he haven't backported it to Atom yet.
