### ISSUE TITLE
Clicking on Avatars Opens in Fullscreen?

### ISSUE THREAD

**Issue by epmatsw** [Floobits/floobits-atom#78]
If you click someone's avatar, it opens their video in a new fullscreen window. It seems like you wouldn't want to do that very often, since it takes you away from the code. It's also especially frustrating if team members are in audio-only mode, since it's hard to tell if they are in the workspace. The end result of that is that you end up with a giant sideways G if you click someone who's already present. It'd be nice to be able to disable this feature at the very least.

**Comment by kans** [comment]
@epmatsw 

You should only see a gravatar when the user is in the workspace.  Is this not the case?

**Comment by epmatsw** [comment]
The gravatar is there, but it doesn't mean that the person is in video chat. I guess my main issue is that it's too easy to accidentally or unintentionally fullscreen a video, and I'm not sure that there's a great use case for being able to do that at all.

**Comment by ggreer** [comment]
Please take a look at the latest version (v0.25.0). Hovering over the thumbnail should say, "start video chat" or "full screen" depending on whether you're already in audio/video chat with the person.

It's not perfect, but it should be much less confusing.

**Comment by epmatsw** [comment]
So...it seems like there's no way to exit full screen now?
1. Join workspace.
2. Click own icon, which starts a video chat(?)
3. Click own icon again to enter fullscreen (nice overlay though!)
4. Click/doubleclick/press esc/exit OSX fullscreen, but stay stuck on a black screen.

Edit: This is only in audio-only mode. Apparently a fullscreen audio element doesn't have a fullscreen toggle element like a fullscreen video element would.

**Comment by kans** [comment]
@epmatsw 

I can't duplicate - in audio only mode, I can click the minimize button or press escape.

**Comment by epmatsw** [comment]
It's very possible this has been fixed since I commented. I have not been using Floobits since, so I can't really confirm either way.
