### ISSUE TITLE
Conflict with linter-flake8

### ISSUE THREAD

**Issue by kepbod** [Floobits/floobits-atom#96]
When I join a workshop, [linter-flake8](https://atom.io/packages/linter-flake8) would report large amount of errors. Please help fix it. Thanks!

**Comment by ggreer** [comment]
Please see [How to Write Good Bug Reports](http://geoff.greer.fm/2015/08/15/how-to-write-good-bug-reports/)

Without any steps to reproduce the issue or specific error messages, it's impossible for me to help. I'll reopen this issue if you comment with more info.
